name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil codingan
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java 17 (Wajib untuk Gradle 8.0+ yang dipakai Flutter baru)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. Install Dependencies
      - name: Get Dependencies
        run: flutter pub get

      # [DEBUG] Cek apakah file gradlew terdeteksi oleh GitHub
      - name: Check Android Directory Contents
        run: ls -la android/

      # 5. Beri izin eksekusi (Ini yang error sebelumnya)
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      # 6. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload Hasil Build
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk